import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/Nav";
import Semibar from "./(components)/Semibar";
import Footer from "./(components)/Footer";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Amazon-clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <Semibar />
        <br />
        <Suspense fallback={<Loading />}>{children}</Suspense>
        <Footer />
      </body>
    </html>
  );
}
